"""add merchant_rules table

Revision ID: be2432f12464
Revises: a4b5c6d7e8f9
Create Date: 2026-04-10 22:04:48.125658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2432f12464'
down_revision: Union[str, Sequence[str], None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_pattern', sa.String(length=500), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('match_field', sa.String(length=20), server_default='merchant_name', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_pattern', 'match_field', name='uq_merchant_rule_per_user')
    )
    op.create_index('ix_merchant_rules_user_id', 'merchant_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchant_rules_user_id', table_name='merchant_rules')
    op.drop_table('merchant_rules')
    # ### end Alembic commands ###
